version: "3.8"

services:
  apache:
    image: httpd:2.4
    container_name: jktdc-apache
    ports:
      - "8080:80"
    volumes:
      - .:/usr/local/apache2/htdocs/:cached
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf:cached
    restart: unless-stopped
